#160037387 Update the favorites feature on the front-end
andela-stuff/andela-teams-2 pull request #11
Opened 2018-09-18 14:27 UTC by Billmike

#### What does this PR do?
Updates the current implementation for adding favorites on the client-side

#### Description of task to be completed?
Update actions and reducers to reflect the new change

2018-09-18 19:27 UTC, Chieze-Franklin requested changes

2018-09-18 19:27 UTC, Chieze-Franklin commented on client/src/modules/HOC/index.jsx
> +const renderCards = (addFavorites, { teams }, favoriteId) => {
I think we can rename some of our variables to make it easier to follow the code. For instance, the variable `favoriteId` should probably be `favorites` since it's an array of `Favorite` models.

2018-09-18 19:27 UTC, Chieze-Franklin commented on client/src/modules/HOC/index.jsx
>    return teams.map(items => {
`items` is a singular team. We can rename it to reflect that. At least it shouldn't be a plural noun.

2018-09-18 19:27 UTC, Chieze-Franklin commented on client/src/modules/HOC/index.jsx
> +    favoriteId.forEach(team => {
The name `team` can be misleading here. The object isn't actually a team but a favorite object.

2018-09-18 19:27 UTC, Chieze-Franklin commented on client/src/modules/HOC/index.jsx
> +    favoriteId.forEach(team => {
I don't know if you still need this code to decide if a team has been favorited. You can simply check the `favoritedByYou` field (like you did on line 34).

2018-09-18 19:33 UTC, Billmike commented on client/src/modules/HOC/index.jsx
> +    favoriteId.forEach(team => {
`favoritedByYou` is not present until an API call is made (in this case a refresh of the page). This code just ensures a visual cue is provided (changing the color of the favorite icon) without refreshing the page.

2018-09-19 15:36 UTC, Chieze-Franklin approved these changes
LGTM!

2018-09-19 15:36 UTC, Chieze-Franklin commented on client/src/modules/HOC/index.jsx
> +          isFavorited={item.favoritedByYou || hasFavorited}
Do we really still need `hasFavorited`?

2018-09-19 15:36 UTC, Chieze-Franklin commented on client/src/modules/HOC/index.jsx
> +    favorites.forEach(team => {
Can we rename this `team` to `favorite` or something similar? Considering the fact that an actual `team` object has a field called `userId`, this can make line `21` a little confusing.

2018-09-19 15:36 UTC, merged